**1-Write a NumPy program to test whether none of the elements of a given array is zero.**

In [5]:
import numpy as np


In [ ]:

arr=np.array([1,2,34,5,7,899,0,4,5,6,3])

np.all(arr==0)



False

**2. Write a NumPy program to test whether any of the elements of a given array is non-zero.**

In [ ]:

arr1=np.array([1,2,34,5,7,899,0,4,5,6,3])

np.any(arr1!=0)


True

**Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.**

In [ ]:

zero_arr = np.zeros(10)
one_arr = np.ones(10)
five_arr = np.full(10,5)

print("Array of 10 zeros:")
print(zero_arr)
print("\nArray of 10 ones:")
print(one_arr)
print("\nArray of 10 fives:")
print(five_arr)


Array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]


**Write a NumPy program to create an array of the integers from 30 to70.**

In [ ]:
arr=np.arange(30, 71)

print(arr)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


**Write a NumPy program to create a 3x3 identity matrix**

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Write a NumPy program to generate a random number between 0 and 1**

In [ ]:
np.random.rand()

0.7759305298776757

**Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution**

In [ ]:
np.random.randn(15)

array([ 0.37618915,  1.87389364,  0.82489968, -0.41231271, -0.60799581,
       -0.20284423, -1.05322931, -0.2568037 ,  2.16402568,  0.99696331,
       -1.27752835,  0.7690472 , -0.4519732 ,  0.57343756, -1.02905996])

**Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.**

In [ ]:

list = np.arange(15, 56)
print(list[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


**Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10**

In [ ]:
np.random.randint(0,10,size=5)

array([1, 1, 2, 1, 4])

**Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
to 1, and inside 0.**

In [ ]:
arr=np.zeros(shape=(10,10))
arr
arr[0, :]= 1
arr[:, 0]= 1
arr[-1, :]= 1
arr[:, -1]= 1
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5**

In [6]:

np.diag([1,2,3,4,5])


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

**Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
diagonal.**

In [ ]:
arr=np.zeros(shape=(4,4))
arr
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
arr

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

**Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.
Select**

In [27]:
np.random.seed(2)
np.random.rand(40)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ,
       0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728,
       0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987,
       0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548,
       0.50524609, 0.0652865 , 0.42812233, 0.09653092, 0.12715997,
       0.59674531, 0.226012  , 0.10694568, 0.22030621, 0.34982629,
       0.46778748, 0.20174323, 0.64040673, 0.48306984, 0.50523672,
       0.38689265, 0.79363745, 0.58000418, 0.1622986 , 0.70075235])

**Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number.**

In [35]:
arr = np.array([1,2,3,4,5])

filt=arr>=4

filt

array([False, False, False,  True,  True])